### ISSUE TITLE
Sync the two db instances of blockscout

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#231]
**Description**
After the latest full reindexing, only one instance of Blockscout contains the full snapshot of data - `blockscout3`.
In order to have a fully-functional stand-by instance of Blockscout, we need to sync database instances `blockscout3` -> `blockscout1`.
Perhaps, restoring from the latest backup from `blockscout3` and indexing the tail of blocks would do the trick.

**Acceptance Criteria**
- [ ] the `blockscout1` db instance contains a copy of `blockscout3`

**Comment by yourbuddyconner** [comment]
Process: 
We are unable to restore a cloudsql server from a backup while it has deployed replicas. In order to achieve this, we will do the following: 

- Delete replicas from the destination DB `rc11` (https://console.cloud.google.com/sql/instances/rc11?project=celo-testnet-production)
- Restore from the backup of `rc13` (https://console.cloud.google.com/sql/instances/rc13/backups?project=celo-testnet-production)
- Re-enable replicas on `rc11`

**Comment by yourbuddyconner** [comment]
The maintenance has been completed successfully.
