### ISSUE TITLE
Archive nodes load balancing

### ISSUE THREAD

**Issue by carterqw2** [celo-org/blockscout#243]
**Description**
Currently, there is a load balancer in front of a number of archive nodes that serve both active and stand-by instances of Blockscout.
In some cases, requests from both instances get routed to the same archive node that results in high CPU usage on the node under load.
We need to guarantee that requests from different instances of Blockscout will be always routed to different archive nodes.

**Acceptance Criteria**
RPC requests from different instances of Blockscout are routed by the load balancer to different archive nodes.

**Relevant URLs**
https://cloud.google.com/load-balancing/docs/backend-service#session_affinity

**Comment by yourbuddyconner** [comment]
Might be the case that node affinity might be our best bet here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by carterqw2** [comment]
It seems that it's unrelated to different instances being deployed to the same k8s node.

**Comment by lvpeschke** [comment]
The immediate issue has been mitigated by:
- making it possible to pin Blockscout to a specific archive node
- adding more archive nodes to the pool
- upsizing the archive node resources
- reducing the traffic by solving some cases of errors (eg: due to how timeouts were configured)

This has morphed into different work streams to more efficiently retrieve data from the archive nodes, see celo-org/blockscout#450.
