### ISSUE TITLE
[BUG] Blockscout no longer has support for "Read Contract" for sourcify verified contracts

### ISSUE THREAD

**Issue by zviadm** [celo-org/blockscout#253]
Verified contract:
https://explorer.celo.org/address/0x2879bfd5e7c4ef331384e908aaa3bd3014b703fa/contracts

There is no "Read Contract" button to actually read contract data on Blockscout.

**Comment by zviadm** [comment]
@carterqw2 : Not sure if there is some special hack that allows "read contract" to work for Core contracts, but one of the main benefits of verifying contracts is to be able to read their data in the explorer. 
Would be great to figure out why reading doesn't work for non Core contracts

**Comment by carterqw2** [comment]
@zviadm thanks, will check.

**Comment by bertux** [comment]
For https://alfajores-blockscout.celo-testnet.org/address/0x612cF8a29A9c8965a5fE512b7463165861c07EAa/contracts it doesn't display anymore the "Read Contract" tab which is not a problem in this specific case because there is nothing to read from this contract but I'm happy to see now the "Write Contract" which I've never seen before in the Blockscout of Celo.
