### ISSUE TITLE
Verified Contracts Page

### ISSUE THREAD

**Issue by mattdkim** [celo-org/blockscout#491]
[Design Here](https://www.figma.com/file/6kK7R685s4h6z0188FfeiG/Blockscout-V1.2?node-id=0%3A1)

Goal: Create a page with a table that lists every verified contract on Celo for the users to easily find. The list should be updated automatically as new contracts get verified. 

Paginate 100 per page
This page goes under "Blockchain" tab in the new nav; see Issue #454 for more detail
The followings are the columns for the table - *contracts are sorted by most recently verified
- Address	
- Check mark + Address (Link)
- Contract Name (Links to the contract address)
- Compiler	
- Version	
- Balance
- Celo balance
- Txns	
- Verified (Date in format MM.DD.YY)
- License (“None” is acceptable value)

**Comment by mattdkim** [comment]
Navigation for the page

![Screen Shot 2022-03-28 at 11.27.39 PM.png](https://images.zenhubusercontent.com/6147a23f6770dab153220bb6/c55b8005-b975-41ed-9667-5b27f743cf98)

**Comment by rkachowski** [comment]
For the sake of velocity I will try to implement as defined, but I want to outline some notes / concerns.
* data taken from smart contract metadata fields, such as compiler version ,aren't reliable unless the contract is fully verified
    * "partial" verification means exactly that - the code matches but the metadata doesn't, so things like "compiler version" and other comments may be incorrect
* as above, we don't actually have the compiler used - and it is possible we will never have it for a given contract. What we do have is the language and that seems to reflect what is wanted in the mockups so I will replace the title "Compilier" with "Language"
* License can be difficult to detect, and "No Licence" can have a rather different legal interpretation from "No Licence Detected", but we can make a best attempt here to try and figure it out
* I'm not sure how accurate "Date" is here - I believe it is in reality "the first time blockscout has seen this contract and found it to be validated" rather than "the date the contract was validated".

**Comment by carterqw2** [comment]
1. That depends on the compiler. Vyper won't compile a smart contract if the version of the compiler is different than the one set in the version comment.
2. Compiler -> Language is good I think.
3. The plan was to explicitly add a separate "License" field later, no need to detect.
4. Date again depends on the scenario (more accurate for Vyper contracts).
5. I agree that Balance is vague, a smart contract could have other tokens than CELO.
6. Right, I think we need clearer definitions in general.

**Comment by rkachowski** [comment]
The majority of contracts contain a `SPDX-License-Identifier:` comment in the source code - I'm just running this through a basic regex to extract the license when possible. Celo contracts don't have this, but it was confirmed by Tim that all celo contracts are "LGPL-3.0" so using our brand new core contract detection feature we can mark this correctly.

I'm not sure how Vyper verification works, but the code has already been compiled and deployed by the point at which solidity contracts are verified via sourcify. This makes it possible that the source files presented for verification are different from the code that was compiled.
